### ISSUE TITLE
Noetic support

### ISSUE THREAD

**Issue by tim-fan** [UbiquityRobotics/dnn_detect#8]
Hi there, just wondering if a release for noetic is likely/possible?

I was able to get a successful build for noetic with the changes in #7, I'm not sure what else is required in order to get this released.

**Comment by davecrawley** [comment]
Thank you for your PR - that's the perfect thing to do. We are expecting to do a noetic release shortly, probably in the next few months.

**Comment by tim-fan** [comment]
Ok great, thanks for the info. I look forward to the release!

**Comment by tim-fan** [comment]
Re-opening to make some more comments;

Thanks for merging #7 . While I was able to build and run on noetic with those changes, I've taken a closer look at my dockerfile, and noticed I was using the -r flag for `rosdep install`, which ignores errors when resolving dependencies. This was masking issues with two dependencies listed in [package.xml](https://github.com/UbiquityRobotics/dnn_detect/blob/kinetic-devel/package.xml):

1. `fiducial_msgs` this has not been released for Noetic, but on the other hand I don't see any use of this package in `dnn_detect`, so I recommend just deleting that line. I've opened #9 for this change.
2. `opencv3` - this is not available in noetic. Reading up on how opencv versions have been supported from kinetic to noetic, my understanding is that the `opencv3` package was created to allow kinetic packages to use opencv3.3.1. This was required for `dnn_detect` in kinetic in order to use the opencv dnn module. In noetic the system installed opencv version 4.2 which includes the dnn module, so it looks like `opencv3` is no longer required, and can be switched to `libopencv-dev`.

Note change (2) will break kinetic, so I assume the change should be made on a `noetic-devel` branch. I've made the change in https://github.com/tim-fan/dnn_detect/tree/noetic-devel, but I believe you need to create a `noetic-devel` branch before I can pull request the change to this repo. So if you'd like to proceed with the change, let me know when the branch is created and I'll open the pull request. 

References:
Discussion on opencv version support for melodic: https://github.com/ros-infrastructure/rep/issues/167
Supported opencv version for noetic: https://www.ros.org/reps/rep-0003.html#noetic-ninjemys-may-2020-may-2025

**Comment by rohbotics** [comment]
Thanks for looking into this, I merged #9. As for a noetic branch, I am not too excited about branching development for such a small package, is it possible that we don't have to directly depend on opencv and have it bring in the correct version automatically by depending on cv_bridge?

If that doesn't seem to work, I am ok with creating a noetic branch.

**Comment by tim-fan** [comment]
Hey, nice idea, I've given that a test (just remove the `opencv3` dep), and it works on my docker builds for both kinetic and noetic - the dependency on `cv_bridge` pulls in a working version of opencv in both cases. So it looks like a new noetic-devel branch wont be needed.

On the one hand I imagine it would preferable to be explicit about such dependencies, rather than relying on other dependencies to pull in the correct thing. However in this case I guess that is outweighed by the desire to keep things simple (single devel branch). I'll create the pull request for this change now.

**Comment by rohbotics** [comment]
@tim-fan I merged your PR. Let me know if everything is working on Noetic now, I will do a release of the package.

Thanks for all the help.

**Comment by tim-fan** [comment]
Last change (hopefully!) : #11 
That came up when I was trying to build/run the test for noetic.
Once that's resolved I'll do a final test for the release.

**Comment by tim-fan** [comment]
Ok, with that change merged, I used the dockerfile from [here](https://github.com/tim-fan/dockerfiles/tree/master/20200805_dnn_detect_noetic_support) to confirm that the kinetic-devel branch builds with noetic, tests pass, and that I can run `dnn_detect.launch` and get detected objects (confirmed I am a `person` sitting on a `sofa` :smile: )

So looks good to me for a noetic release :+1:

**Comment by Alex-Beh** [comment]
Hello, can I use this dnn_detect with opencv_3.4? I try use the package with the following two command:
`roslaunch usb_cam usb_cam-test.launch`
`roslaunch dnn_detect dnn_detect.launch camera:=/usb_cam image:=image_raw
`

And it raised the following error:

> cv exception: /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/core/src/matrix.cpp:1032: error: (-215) dims <= 2 in function reshape

I try to print out the shape of the cv_ptr->image that pass into resize function and it is [640,480]. The package can only be used on compressed image as input?

-----
**Update:** Solved by git clone the cv_bridge and checkout the melodic branch.
